[package]
org = "exco"
name = "pdf_converter"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "com.google.auth"
artifactId = "google-auth-library-oauth2-http"
version = "1.19.0"

# transitive dependency of com.google.auth:google-auth-library-oauth2-http:1.19.0
[[platform.java11.dependency]]
groupId = "com.google.auto.value"
artifactId = "auto-value-annotations"
version = "1.10.1"

# transitive dependency of com.google.auth:google-auth-library-oauth2-http:1.19.0
[[platform.java11.dependency]]
groupId = "com.google.code.findbugs"
artifactId = "jsr305"
version = "3.0.2"

# transitive dependency of com.google.auth:google-auth-library-oauth2-http:1.19.0
[[platform.java11.dependency]]
groupId = "com.google.auth"
artifactId = "google-auth-library-credentials"
version = "1.19.0"

# transitive dependency of com.google.auth:google-auth-library-oauth2-http:1.19.0
[[platform.java11.dependency]]
groupId = "com.google.http-client"
artifactId = "google-http-client"
version = "1.42.3"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpclient"
version = "4.5.13"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "commons-logging"
artifactId = "commons-logging"
version = "1.2"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "commons-codec"
artifactId = "commons-codec"
version = "1.11"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpcore"
version = "4.4.15"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "com.google.errorprone"
artifactId = "error_prone_annotations"
version = "2.16"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "com.google.j2objc"
artifactId = "j2objc-annotations"
version = "1.3"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "io.opencensus"
artifactId = "opencensus-api"
version = "0.31.1"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "io.grpc"
artifactId = "grpc-context"
version = "1.27.2"

# transitive dependency of com.google.http-client:google-http-client:1.42.3
[[platform.java11.dependency]]
groupId = "io.opencensus"
artifactId = "opencensus-contrib-http-util"
version = "0.31.1"

# transitive dependency of com.google.auth:google-auth-library-oauth2-http:1.19.0
[[platform.java11.dependency]]
groupId = "com.google.http-client"
artifactId = "google-http-client-gson"
version = "1.42.3"

# transitive dependency of com.google.http-client:google-http-client-gson:1.42.3
[[platform.java11.dependency]]
groupId = "com.google.code.gson"
artifactId = "gson"
version = "2.10"

# transitive dependency of com.google.auth:google-auth-library-oauth2-http:1.19.0
[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "32.0.0-android"

# transitive dependency of com.google.guava:guava:32.0.0-android
[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "failureaccess"
version = "1.0.1"

# transitive dependency of com.google.guava:guava:32.0.0-android
[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "listenablefuture"
version = "9999.0-empty-to-avoid-conflict-with-guava"

# transitive dependency of com.google.guava:guava:32.0.0-android
[[platform.java11.dependency]]
groupId = "org.checkerframework"
artifactId = "checker-qual"
version = "3.33.0"
